# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 06:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 13, 6, 12, 13, 373171, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
